appfolio_update2_updated
ucsb-ds-capstone-2021/ucsb-ds-capstone-2021.github.io pull request #37
Opened 2021-03-16 02:46 UTC by Pinkaban

2021-03-19 17:26 UTC, syoh requested changes

2021-03-19 17:26 UTC, syoh commented on ucsb_ds_capstone_projects_2021/projects/appfolio/update2.md
> +![FUNSDpred](https://github.com/DSCapstone2021/ucsb-ds-capstone-2021.github.io/blob/main/ucsb_ds_capstone_projects_2021/projects/appfolio/FUNSDpred.png?raw=true)
For the image `FUNSDpred.png` in the same directory as the markdown file, you can use `![some-text](FUNSDpred.png)` 
Refer to https://jupyterbook.org/content/figures.html for more info

2021-03-19 17:26 UTC, syoh commented on ucsb_ds_capstone_projects_2021/projects/appfolio/update2.md
> +![Invoice_Label](https://github.com/DSCapstone2021/ucsb-ds-capstone-2021.github.io/blob/main/ucsb_ds_capstone_projects_2021/projects/appfolio/Invoice_Label.PNG?raw=true)
Same here

For the image `FUNSDpred.png` in the same directory as the markdown file, you can use `![some-text](FUNSDpred.png)` 
Refer to https://jupyterbook.org/content/figures.html for more info

2021-03-19 19:54 UTC, Pinkaban reviewed
I have made the changes suggested by @syoh. Thank you professor for the suggestions!

2021-03-20 01:31 UTC, syoh approved these changes
looks good

2021-03-20 01:31 UTC, merged