Revised Progress update 2
ucsb-ds-capstone-2021/ucsb-ds-capstone-2021.github.io pull request #42
Opened 2021-03-18 22:05 UTC by lawrencedlin

Implemented feedback suggestions

2021-03-19 16:58 UTC, syoh requested changes

2021-03-19 16:58 UTC, syoh commented on ucsb_ds_capstone_projects_2021/projects/sansum/update2.md
>  <img src = "https://raw.githubusercontent.com/lawrencedlin/ucsb-ds-capstone-2021.github.io/main/ucsb_ds_capstone_projects_2021/projects/sansum/visuals/pca.png" width = 200px, height = 200px>
Markdown can embed images directly: https://jupyterbook.org/content/figures.html
For the image `visuals/pca.png`, replace the HTML with `![some-text](visuals/pca.png)`

2021-03-19 16:58 UTC, syoh commented on ucsb_ds_capstone_projects_2021/projects/sansum/update2.md
> +<img src = "https://raw.githubusercontent.com/lawrencedlin/ucsb-ds-capstone-2021.github.io/main/ucsb_ds_capstone_projects_2021/projects/sansum/visuals/zipcode.png" width = 400px height = 300px>
Same here

Markdown can embed images directly: https://jupyterbook.org/content/figures.html
For the image `visuals/someimg.png`, replace the HTML with `![some-text](visuals/someimg.png)`

2021-03-19 16:58 UTC, syoh commented on ucsb_ds_capstone_projects_2021/projects/sansum/update2.md
> +<img class = "resize" src = "https://raw.githubusercontent.com/lawrencedlin/ucsb-ds-capstone-2021.github.io/main/ucsb_ds_capstone_projects_2021/projects/sansum/visuals/diagnosis.png" width = 500px, h
Same here

Markdown can embed images directly: https://jupyterbook.org/content/figures.html
For the image `visuals/someimg.png`, replace the HTML with `![some-text](visuals/someimg.png)`

2021-03-19 16:58 UTC, syoh commented on ucsb_ds_capstone_projects_2021/projects/sansum/update2.md
> +<img src = "https://raw.githubusercontent.com/lawrencedlin/ucsb-ds-capstone-2021.github.io/main/ucsb_ds_capstone_projects_2021/projects/sansum/visuals/survey.png">
Same here

Markdown can embed images directly: https://jupyterbook.org/content/figures.html
For the image `visuals/someimg.png`, replace the HTML with `![some-text](visuals/someimg.png)`

2021-03-20 04:27 UTC, lawrencedlin commented
Images embedded in the markdown file now

2021-03-26 05:00 UTC, merged